---
# tasks file for roles/setup
- name: disable password on wheel
  lineinfile:
          dest: /etc/sudoers
          state: present
          regexp: "^ %wheel ALL=(ALL) ALL"
          line: "# %wheel ALL=(ALL) ALL"
- name: enable passwordless on wheel
  lineinfile:
          dest: /etc/sudoers
          state: present
          regexp: "^# %wheel ALL=(ALL) NOPASSWD: ALL"
          line: "%wheel ALL=(ALL) NOPASSWD: ALL"
- name: disbale SELINUX
  lineinfile:
          dest: /etc/SELINUX/config
          state: present
          regexp: 'SELINUX=enforcing'
          line: 'SELINUX=disabled'
          backup: yes
- name: enforce selinux
  command: echo 0 > /sys/fs/selinux/enforce
- name: reboot
  command: reboot
  poll: 0
- name: enable ip forwarding
  lineinfile:
          dest: /etc/sysctl.conf
          line: "net.ipv4.ip_forward = 1"
          insertafter: EOF
- name: ip forward to 1
  sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_set: yes
- name: enable ip forwarding w/o reboot
  command: systctl -w net.ipv4.ip_forward=1
- name: update system
  yum: name=* state=latest update_cache=true
- name: install packages 
  yum: name={{ item }} state=installed update_cache=true
  with_items:
          - "{{ packages }}"
- name: firewall zone configuration
  firewalld:
          zone: external
          interface: ens160
          permanent: true
          state: enabled
- name: firewall zone config internal
  firewalld:
          zone: internal
          interface: "{{ item }}"
          permanent: true
          state: enabled
  with_items:
          - "{{ internal_interface }}"
- name: masquerade on the externals
  firewalld:
          zone: external
          masquerade: yes
          permanent: true
- name: NAT
  command: firewall-cmd --permanent --direct --passthrough ipv4 -t nat -l POSTROUTING -o ens160 -j MASQUERADE -s 172.16.1.0/24
- name: Enable services on internal
  firewalld:
          zone: internal
          service: "{{ item }}"
          permanent: true
  with_items: "{{ services }}"
- name: reload firewall
  command: firewall-cmd --complete-reload
- name: install dhcp
  yum: name=dhcp state=installed update_cache=true
- name: empty dhcpd conf file
  command: echo "#" > /usr/share/doc/dhcp-4.2.5/dhcpd.conf.example
- name: cp dhcpd.service to dhcpd.conf
  copy:
          src: /usr/share/doc/dhcp-4.2.5/dhcpd.conf.example
          dest: /etc/dhcp/dhcpd.conf
          remote_src: yes
- name: copy dhcp_service
  copy:
          src: /usr/lib/systemd/system/dhcpd.service
          dest: /etc/systemd/system/
          remote_src: yes
- name: EXEC
  lineinfile:
          dest: /etc/systemd/system/dhcpd.service
          state: present
          regexp: "^ExecStart=/usr/sbin/dhcpd -f -cf /etc/dhcp/dhcpd.conf -user dhcpd -group dhcpd --no-pid"
          line: "ExecStart=/usr/lib/dhcpd -f -cf /etc/dhcp/dhcpd.conf -user dhcpd -group dhcpd --no-pid ens192"

